name: Publish Release

on:
  push:
    branches:
      - main  # Ou la branche que vous utilisez pour le déploiement

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'  # Remplacez par la version .NET utilisée

      - name: Build project
        run: dotnet publish --configuration Release

      # Création d'une Release
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 'v1.0.${{ github.run_number }}'  # Tag de version dynamique
          release_name: 'Release v1.0.${{ github.run_number }}'
          draft: false
          prerelease: false

      # Téléchargement des fichiers de plus de 100 Mo dans la Release
      - name: Upload MSI or EXE to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./publish # Chemin vers votre fichier généré (même s'il dépasse 100 Mo)
          asset_name: NtlmGithubManager.exe  # Nom de votre fichier
          asset_content_type: application/octet-stream
