# À partir de l'étape 8 pour le débogage

jobs:
  release:
    runs-on: windows-latest

    steps:
      # 8. Checkout du dépôt ntlm-technologies/lgi
      - name: Checkout LGI repository
        uses: actions/checkout@v4
        with:
          repository: 'ntlm-technologies/lgi'  # Cloner le dépôt LGI
          token: ${{ secrets.PAT_TOKEN }}  # Utiliser le PAT que vous avez généré
          path: './lgi'

      # 9. Simuler une modification du README.md (remplacez le lien EXE par autre chose pour les tests)
      - name: Update README.md with a test link
        run: |
          sed -i 's|Téléchargez .*|Téléchargez ici un lien test: https://example.com|' ./lgi/README.md

      # 10. Committer et pousser le README.md modifié (test)
      - name: Commit and push updated README.md
        run: |
          git config --global user.email "mambojoel@gmail.com"
          git config --global user.name "Nicolas Taret"
          cd lgi
          git add README.md
          git commit -m "Update README.md with test link"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}  # Utiliser PAT pour les permissions d'écriture
