name: Create Release

on:
  push:
    branches:
      - main  # Ou la branche de votre choix

jobs:
  release:
    runs-on: windows-latest  # Utiliser un environnement Windows

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'  # Spécifiez la version de .NET

      - name: Build project
        run: dotnet publish --configuration Release

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 'v1.0.${{ github.run_number }}'
          release_name: 'Release v1.0.${{ github.run_number }}'
          draft: false
          prerelease: false

      - name: Upload EXE to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./publish # Chemin vers votre fichier généré (même s'il dépasse 100 Mo)
          asset_name: NtlmGithubManager.exe  # Nom de votre fichier
          asset_content_type: application/octet-stream
