name: Create Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v4  # Mise à jour vers v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4  # Mise à jour vers v4
        with:
          dotnet-version: '8.x'

      - name: Build project
        run: dotnet publish ntlm.Damien.Win.csproj --configuration Release  # Ajuster le projet à publier

      - name: Verify if build files exist
        run: |
          echo "Checking if build files exist..."
          ls -la ./publish

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: 'v1.0.${{ github.run_number }}'
          name: 'Release v1.0.${{ github.run_number }}'
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}  # Ou réessayez avec ${{ secrets.GITHUB_TOKEN }}

      - name: Upload EXE to Release
        uses: actions/upload-release-asset@v1
        continue-on-error: true  # Continue même en cas d'erreur
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./publish/NtlmGithubManager.exe
          asset_name: NtlmGithubManager.exe
          asset_content_type: application/octet-stream
