name: Create Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: windows-latest
    
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with: 
          dotnet-version: '8.x'

      - name: Build project
        run: dotnet publish ./ntlm.Damien.Win/ntlm.Damien.Win.csproj --configuration Release --output ./publish

      - name: Verify build output
        run: |
          echo "Listing contents of the publish directory:"
          Get-ChildItem ./publish

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: 'v1.0.${{ github.run_number }}'
          release_name: 'Release v1.0.${{ github.run_number }}'
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload EXE to Release
        uses: actions/upload-release-asset@v1  # Upload le fichier dans la release.
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}  # URL pour uploader l'asset.
          asset_path: ./publish/NtlmGithubManager.exe  # Chemin vers l'exécutable.
          asset_name: NtlmGithubManager.exe  # Nom sous lequel le fichier sera listé.
          asset_content_type: application/octet-stream  # Type de contenu (binaire).
