name: Create Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build project
        run: dotnet publish ./ntlm.Damien.Win/ntlm.Damien.Win.csproj --configuration Release --output ./publish

      - name: Verify build output
        run: |
          echo "Listing contents of the publish directory:"
          Get-ChildItem ./publish

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1  # Utiliser l'action officielle de création de release
        with:
          tag_name: 'v1.0.${{ github.run_number }}'
          release_name: 'Release v1.0.${{ github.run_number }}'
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}  # Utiliser le GITHUB_TOKEN ici

      - name: Upload EXE to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./publish/NtlmGithubManager.exe
          asset_name: NtlmGithubManager.exe
          asset_content_type: application/octet-stream
