name: Create Issue Test

on:
  push:
    branches:
      - main

jobs:
  test-github-token:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v4

      - name: Create a test issue using GITHUB_TOKEN
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: "Test issue for GITHUB_TOKEN"
          content-filepath: ./test-issue.md
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify token
        run: echo "Testing GITHUB_TOKEN access"
