name: Create Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v4  # Utilisation de l'action standard pour cloner le dépôt

      - name: Set up .NET
        uses: actions/setup-dotnet@v4  # Utilisation de l'action standard pour configurer .NET
        with:
          dotnet-version: '8.x'

      - name: Build project
        run: dotnet publish ./ntlm.Damien.Win/ntlm.Damien.Win.csproj --configuration Release --output ./publish

      - name: Verify build output
        run: |
          echo "Listing contents of the publish directory:"
          Get-ChildItem ./publish  # Lister les fichiers publiés pour vérification

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1  # Action officielle pour créer une release
        with:
          tag_name: 'v1.0.${{ github.run_number }}'
          release_name: 'Release v1.0.${{ github.run_number }}'
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Passer explicitement le token GitHub

      - name: Log upload_url  # Ajouter un log pour vérifier l'URL d'upload
        run: |
          echo "Upload URL: ${{ steps.create_release.outputs.upload_url }}"  # Afficher l'URL d'upload

      - name: Upload EXE to Release
        uses: actions/upload-release-asset@v1  # Utilisation de l'action standard pour uploader l'asset
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}  # Utiliser l'URL d'upload renvoyée par create_release
          asset_path: ./publish/NtlmGithubManager.exe
          asset_name: NtlmGithubManager.exe
          asset_content_type: application/octet-stream
